// <auto-generated />
using System;
using Infrastructura.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructura.Migrations
{
    [DbContext(typeof(GastosContext))]
    [Migration("20260511011307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Categoria", b =>
                {
                    b.OwnsOne("LogicaNegocio.VO.VONombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("CategoriaId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Nombre");

                            b1.HasKey("CategoriaId");

                            b1.ToTable("Categorias");

                            b1.WithOwner()
                                .HasForeignKey("CategoriaId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Gasto", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.VO.VODescripcion", "Descripcion", b1 =>
                        {
                            b1.Property<int>("GastoId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Descripcion");

                            b1.HasKey("GastoId");

                            b1.ToTable("Gastos");

                            b1.WithOwner()
                                .HasForeignKey("GastoId");
                        });

                    b.OwnsOne("LogicaNegocio.VO.VOPrecio", "Precio", b1 =>
                        {
                            b1.Property<int>("GastoId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Precio");

                            b1.HasKey("GastoId");

                            b1.ToTable("Gastos");

                            b1.WithOwner()
                                .HasForeignKey("GastoId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Descripcion")
                        .IsRequired();

                    b.Navigation("Precio")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
